export const COMPANIES = [
  {
    title: "Heliowater",
    description: "De l'eau potable en autonomie pendant 30 ans ",
    url: "https://www.heliowater.fr",
    instagram: "https://www.instagram.com/heliowater/",
    season: 3,
  },
  {
    title: "Les mains de mamie",
    description: "Apprends à fabriquer tes fringues avec le Mamy Gang",
    url: "https://www.lesmainsdemamie.com/",
    instagram: "https://www.instagram.com/lesmainsdemamie/",
    season: 3,
  },
  {
    title: "Bob - Daan tech",
    description: "Le lave-vaisselle pour les nerds, par les nerds",
    url: "https://daan.tech/fr/produit/bob-mini-lave-vaisselle/",
    instagram: "https://www.instagram.com/daan_tech_fr/",
    season: 3,
  },
  {
    title: "Resap - Paris",
    description: "Apprends à fabriquer tes fringues avec des déchets",
    url: "https://resap-paris.com/",
    instagram: "https://www.instagram.com/resap_paris/",
    season: 3,
  },
  {
    title: "NKD Puzzle",
    description: "Les Rubik's cubes du metavers",
    url: "https://nkd-puzzle.com/fr/",
    instagram: "https://www.instagram.com/nkdpuzzle/",
    season: 3,
  },
  {
    title: "Aglaé",
    description: "La forêt de Avatar dans ton jardin",
    url: "https://www.design-aglae.com/",
    instagram: "https://www.instagram.com/design.aglae",
    season: 3,
  },
  {
    title: "Unbottled",
    description: "Le savon solide qui te fait voyager",
    url: "https://unbottled.co/",
    instagram: "https://www.instagram.com/unbottled.co/",
    season: 3,
    episode: 1,
  },
];
